### ISSUE TITLE
Update History panel

### ISSUE THREAD

**Issue by DarcieF** [Parrit/Parrit#79]
**Steps:**
- [x] Reference Tracker stories
- [x] Map out quick design updates
- [x] Refine visuals in Figma
- [x] Add updated designs to Tracker stories

**Acceptance:**
Tracker stories for History have been updated and Needs Design label removed.

**References:**
https://www.pivotaltracker.com/story/show/176018739
https://www.pivotaltracker.com/story/show/176018731
